### PR TITLE
Created basic page layout -> Header, main, Footer

### PR DESCRIPTION
**Pull request by A91y**
Added components such as Navbar, Footer, Header (wrapper for Navbar), updated App.css for basic elements.
Future plans: App.css -> styled components

### CODE REVIEW

**Comment by ShreyaPrasad1209** [comment]
@A91y can you look into the merge conflicts?

**Comment by A91y** [comment]
> @A91y can you look into the merge conflicts?

Working on it!
Is it worth merging? Or should I reformat the code completely?

**Comment by ShreyaPrasad1209** [comment]
> > @A91y can you look into the merge conflicts?
> 
> Working on it! Is it worth merging? Or should I reformat the code completely?

@A91y since we already have a Navbar, we can go ahead with main and footer. I reviewed your code and here are few suggestions:

- Files with only whitespace changes were committed which are not related to the code. Was that because of prettier formatting?
- Inside components, we create new folders for new components. You can refer to the main branch for folder structure and file naming conventions.
- Also refer my code to understanding how I'm using styled components and classNames.

**Comment by A91y** [comment]
Closed the PR for now, suggestions will be implemented in fresh new PR.

**Pull request closed without merging**
